# Generated by Django 3.2.25 on 2025-10-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='horarios_disponiveis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
