# Generated by Django 5.2.7 on 2025-10-24 18:34
 
import core.models
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('core', '0001_initial'),
    ]
 
    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='horarios_disponiveis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
 