# Generated by Django 5.2.7 on 2025-10-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Aprovado pelo Admin'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(fields=('nutricionista', 'data_horario'), name='unique_appointment_time'),
        ),
    ]
