# Generated by Django 3.2.25 on 2025-11-12 00:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nutricionista_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
    ]
