# Generated by Django 3.2.25 on 2025-12-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251111_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='duracao',
            field=models.IntegerField(default=60, help_text='Duração em minutos desta consulta'),
        ),
    ]
